
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(S.SALES * B.PRICE) AS TOTAL_SALES
FROM BOOK B JOIN AUTHOR A USING(AUTHOR_ID) JOIN BOOK_SALES S USING(BOOK_ID)
WHERE DATE_FORMAT(S.SALES_DATE,"%Y-%m") = "2022-01" 
GROUP BY A.AUTHOR_ID, B.CATEGORY
ORDER BY A.AUTHOR_ID, B.CATEGORY DESC