SELECT A.APNT_NO, P.PT_NAME, A.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM PATIENT P INNER JOIN APPOINTMENT A USING(PT_NO) INNER JOIN DOCTOR D ON(A.MDDR_ID=D.DR_ID)
WHERE A.APNT_CNCL_YMD IS NULL AND  A.MCDP_CD="CS" AND A.APNT_YMD LIKE "2022-04-13%"
ORDER BY APNT_YMD