SELECT MCDP_CD AS 진료과코드, count(DATE_FORMAT(APNT_YMD, "%Y-%m-%d")) AS 5월예약건수
FROM APPOINTMENT
WHERE DATE_FORMAT(APNT_YMD, "%Y-%m") = "2022-05"
GROUP BY MCDP_CD 
ORDER BY count(DATE_FORMAT(APNT_YMD, "%Y-%m-%d")), MCDP_CD